% Script comparing hist vs bar.
% Author: Chris B. Kirov
% Date: 16.09.2017 
clc
clear
close all

% Generate normally distributed numbers.
n = randn(1, 1000);

subplot(2, 1, 1);
hist(n, 'facecolor', 'g', 'edgecolor', 'b');                % Plot with hist() using one vector input: plot a histogram with 10 bins.
title('Hist plot with data generated by randn()');

[x, binCenters] = hist(n);                                     % Generate values with hist() using two output arguments used for bar() input.

subplot(2, 1, 2);
bar(binCenters, x);                                                % Plot with bar.
title('Bar plot with data generated by hist()');

absolutepath = 'D:\Matlab Projects\Intro to MATLAB - Octave\';
filename = sprintf('%sChapter11Exercise4.pdf', absolutepath);
print(fh, filename);
